2025-01-31 20:05:29,465 [ERROR] _handle_response (http.py:51): [HTTP]接口请求异常，请求连接: https://api.sgroup.qq.com/gateway/bot, error: 401, 返回内容: b'{"message":"\xe6\x8e\xa5\xe5\x8f\xa3\xe8\xae\xbf\xe9\x97\xae\xe6\xba\x90IP\xe4\xb8\x8d\xe5\x9c\xa8\xe7\x99\xbd\xe5\x90\x8d\xe5\x8d\x95","code":11298,"err_code":40023002,"trace_id":"ce9dde8fa09a16e6926f27aaed2c599f"}', trace_id:ce9dde8fa09a16e6926f27aaed2c599f
2025-01-31 20:45:59,883 [ERROR] _handle_response (http.py:51): [HTTP]接口请求异常，请求连接: https://api.sgroup.qq.com/gateway/bot, error: 401, 返回内容: b'{"message":"\xe6\x8e\xa5\xe5\x8f\xa3\xe8\xae\xbf\xe9\x97\xae\xe6\xba\x90IP\xe4\xb8\x8d\xe5\x9c\xa8\xe7\x99\xbd\xe5\x90\x8d\xe5\x8d\x95","code":11298,"err_code":40023002,"trace_id":"18b5623224f4260f4b1a996542aa3fe3"}', trace_id:18b5623224f4260f4b1a996542aa3fe3
